-- Company websites, verified reachable on 2026-09-13.
-- Kept separate from seed.sql because these were gathered by hand rather than
-- extracted from the legacy playbook, and because re-running the seed must not
-- wipe them. Blank entries are deliberate: an unverified link is worse than no
-- link when you are standing in front of a booth.

update companies as c set website = v.url
from (values
  ('absolute', 'absolutemachine.com'),
  ('big', 'bigdaishowa.com'),
  ('blum', 'blum-novotest.com'),
  ('ceratizit', 'ceratizitusa.com'),
  ('chiron', 'chiron-group.com'),
  ('cte', 'ctemag.com'),
  ('datron', 'datron.com'),
  ('dn', 'dnsolutions.com'),
  ('ellison', 'ellisontechnologies.com'),
  ('erowa', 'erowa.com'),
  ('eurotech', 'eurotechcorp.com'),
  ('expand', 'expandmachinery.com'),
  ('fastems', 'fastems.com'),
  ('flexx', 'flexxbotics.com'),
  ('formic', 'formic.co'),
  ('globalcnc', 'globalcnc.com'),
  ('haas', 'haascnc.com'),
  ('haastool', 'haastooling.com'),
  ('haimer', 'haimer-usa.com'),
  ('halter', 'haltercncautomation.com'),
  ('heller', 'heller.biz'),
  ('hermle', 'hermle.de'),
  ('hub', 'practicalmachinist.com'),
  ('hurco', 'hurco.com'),
  ('hwacheon', 'hwacheon.com'),
  ('index', 'index-traub.com'),
  ('jmpp', 'jmperformanceproducts.com'),
  ('jtekt', 'jtektmachinery.com'),
  ('kennametal', 'kennametal.com'),
  ('kent', 'kentusa.com'),
  ('kern', 'kern-microtechnik.com'),
  ('kitamura', 'kitamura-machinery.com'),
  ('koma', 'komaprecision.com'),
  ('kuka', 'kuka.com'),
  ('lang', 'lang-technik.de'),
  ('makino', 'makino.com'),
  ('marposs', 'marposs.com'),
  ('matsuura', 'matsuurausa.com'),
  ('mazak', 'mazakusa.com'),
  ('mcm', 'mcmachinery.com'),
  ('melco', 'mitsubishielectric.com'),
  ('methods', 'methodsmachine.com'),
  ('morris', 'morrisgroupinc.com'),
  ('msc', 'mscdirect.com'),
  ('mst', 'mst-corp.co.jp'),
  ('okuma', 'okuma.com'),
  ('omega', 'omegatmm.com'),
  ('phillips', 'phillipscorp.com'),
  ('platinum', 'platinumtooling.com'),
  ('productivity', 'productivity.com'),
  ('regofix', 'rego-fix.com'),
  ('renishaw', 'renishaw.com'),
  ('robojob', 'robojob.eu'),
  ('royal', 'royalproducts.com'),
  ('sandvik', 'sandvik.coromant.com'),
  ('schunk', 'schunk.com'),
  ('shars', 'shars.com'),
  ('shops', 'mmsonline.com'),
  ('tdm', 'tdmsystems.com'),
  ('trak', 'trakmt.com'),
  ('ur', 'universal-robots.com'),
  ('vention', 'vention.io'),
  ('versabuilt', 'versabuilt.com'),
  ('wintool', 'wintool.com'),
  ('xometry', 'xometry.com'),
  ('yamazen', 'yamazen.com'),
  ('yg1', 'yg1.kr'),
  ('zoller', 'zoller.info')
) as v(id, url)
where c.id = v.id and c.website is null;
