// One-time extraction of TARGETS + INFO from the legacy playbook HTML
// into supabase/seed.sql. Run: node scripts/extract.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const html = readFileSync('hippsc-imts-2026-playbook.html', 'utf8')

function sliceBetween(source, startMarker, endMarker) {
  const start = source.indexOf(startMarker)
  if (start === -1) throw new Error(`marker not found: ${startMarker}`)
  const end = source.indexOf(endMarker, start + startMarker.length)
  if (end === -1) throw new Error(`end marker not found after ${startMarker}`)
  return source.slice(start, end + endMarker.length)
}

// TARGETS is a JS array literal; INFO is built by Object.assign calls.
const targetsSrc = sliceBetween(html, 'var TARGETS=[', '\n];')
const infoStart = html.indexOf('var INFO={};')
const infoEnd = html.indexOf('var HALL=')
if (infoStart === -1 || infoEnd === -1) throw new Error('INFO block not found')
const infoSrc = html.slice(infoStart, infoEnd)

// Evaluate both in a sandboxed-enough scope: this is our own trusted file.
const TARGETS = new Function(`${targetsSrc}\nreturn TARGETS;`)()
const INFO = new Function(`${infoSrc}\nreturn INFO;`)()

console.log(`targets: ${TARGETS.length}, info entries: ${Object.keys(INFO).length}`)

const q = (value) => {
  if (value === undefined || value === null || value === '') return 'null'
  return `'${String(value).replace(/'/g, "''")}'`
}

const qArray = (values) => {
  if (!values || values.length === 0) return `'{}'`
  const inner = values.map((v) => `"${String(v).replace(/"/g, '\\"')}"`).join(',')
  return `'{${inner.replace(/'/g, "''")}}'`
}

const rows = TARGETS.map((t) => {
  const info = INFO[t.id] || {}
  return `  (${q(t.id)}, ${q(t.n)}, ${q(t.t)}, ${qArray(t.b)}, ${q(info.ty)}, ${q(info.hq)}, ${q(t.a)}, ${q(t.w)}, ${q(info.bio)}, ${q(info.fit)}, ${q(info.op)}, ${qArray(info.ak)}, ${q(info.wa)}, true, false)`
})

const sql = `-- Generated by scripts/extract.mjs from hippsc-imts-2026-playbook.html
-- ${TARGETS.length} default companies. Re-runnable: existing ids are left alone.

insert into companies
  (id, name, tier, booths, company_type, hq, ask, who, bio, fit, opening_line, asks, watch_out, is_default, archived)
values
${rows.join(',\n')}
on conflict (id) do nothing;

insert into visits (company_id, visited)
select id, false from companies
on conflict (company_id) do nothing;
`

writeFileSync('supabase/seed.sql', sql)
console.log(`wrote supabase/seed.sql (${rows.length} rows)`)
